server:
  port: 9002

spring:
  application:
    name: TestConsumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://120.77.222.194:9888/eureka/