server:
  port: 8182

spring:
  application:
    name: XDTestService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://120.77.222.194:9888/eureka/
